pipeline:
  install:
    image: node:latest
    commands:
      - node -v
      - npm -v
      - npm install
    when:
      branch:
      - master
      event:
      - push

  testing:
    image: node:latest
    group: testing
    commands:
      - npm run test
    when:
      branch:
      - master
      event:
      - push

