DomainTitle:
  SectionTitle:
    config_file:
      value: __tests__/input/Configuration.yml
      desc: the timetrap config file path
      options: ''
    working_directory:
      value: /tmp
      desc: the working directory with no timetrap-sheet files in it or it's parents
      options: ''
    create_missing_sheets:
      value: false
      desc: create missing sheets from name hiarchy
      options: true|false
    developer_mode:
      value: false
      desc: run in development mode
      options: true|false
    question_prompts:
      value: true
      desc: whether to use 'Are you sure?' dialog prompts
      options: true|false
    color_theme:
      value: opaque
      desc: The color theme to use for the application
      options: dark|light|opaque
